# Generated by Django 4.2.1 on 2023-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0010_space_is_homepage"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarked_spaces",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_users", to="spaces.space"
            ),
        ),
    ]
