# Generated by Django 4.2.1 on 2023-05-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0013_space_cloned_from"),
        ("authentication", "0003_remove_user_bookmarked_spaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_users",
                to="spaces.space",
            ),
        ),
    ]
