export { default as MostlyCloudySvg } from "./svgs/001 Mostly Cloudy.svg";
export { default as PartlyCloudyNightSvg } from "./svgs/002 Partly Cloudy Night.svg";
export { default as BlizzardSvg } from "./svgs/003 Blizzard.svg";
export { default as ClearNightSvg } from "./svgs/004 Clear Night.svg";
export { default as MostlySunnySvg } from "./svgs/005 Mostly Sunny.svg";
export { default as PartlyCloudySvg } from "./svgs/006 Partly Cloudy.svg";
export { default as SunsetSvg } from "./svgs/007 Sunset.svg";
export { default as SunriseSvg } from "./svgs/008 Sunrise.svg";
export { default as HotSvg } from "./svgs/009 Hot.svg";
export { default as BreezySvg } from "./svgs/010 Breezy.svg";
export { default as RainSvg } from "./svgs/011 Rain.svg";
export { default as FogSvg } from "./svgs/012 Fog.svg";
export { default as MixRainfallSvg } from "./svgs/013 Mix Rainfall.svg";
export { default as SnowSvg } from "./svgs/014 Snow.svg";
export { default as ScatteredThundersormSvg } from "./svgs/015 Scattered Thundersorm.svg";
export { default as TornadoSvg } from "./svgs/016 Tornado.svg";
export { default as TropicalStormSvg } from "./svgs/017 Tropical Storm.svg";
export { default as HailSvg } from "./svgs/018 Hail.svg";
export { default as BlowingSnowSvg } from "./svgs/019 Blowing Snow.svg";
export { default as DrizzleSvg } from "./svgs/020 Drizzle.svg";
export { default as DustSvg } from "./svgs/021 Dust.svg";
export { default as HurricaneSvg } from "./svgs/022 Hurricane.svg";
export { default as ScatteredShowersSvg } from "./svgs/023 Scattered Showers.svg";
export { default as SleetSvg } from "./svgs/024 Sleet.svg";
export { default as IceSvg } from "./svgs/025 Ice.svg";
export { default as HazeSvg } from "./svgs/026 Haze.svg";
export { default as SmokeSvg } from "./svgs/027 Smoke.svg";
export { default as NoReportSvg } from "./svgs/028 No Report.svg";
