# Generated by Django 4.2.1 on 2023-05-20 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="link",
        ),
    ]
