# Generated by Django 4.2.1 on 2023-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0003_alter_widget_widget_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="card_style",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
