# Generated by Django 4.2.1 on 2023-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0004_widget_card_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="card_style",
            field=models.JSONField(default=dict),
        ),
    ]
