# Generated by Django 4.2.1 on 2023-05-23 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
        ("spaces", "0006_alter_widget_widget_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="widgets",
                to="links.link",
            ),
        ),
    ]
