# Generated by Django 4.2.1 on 2023-05-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0007_widget_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="access",
            field=models.IntegerField(
                choices=[(1, "Private"), (2, "Public"), (3, "Share Url")], default=1
            ),
        ),
    ]
