# Generated by Django 4.2.1 on 2023-05-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0008_space_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="access",
            field=models.IntegerField(
                choices=[(1, "Private"), (2, "Public")], default=1
            ),
        ),
    ]
