# Generated by Django 4.2.1 on 2023-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0009_alter_space_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="is_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
