# Generated by Django 4.2.1 on 2023-05-27 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spaces", "0010_space_is_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
