# Generated by Django 4.2.1 on 2023-05-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0012_space_description_alter_space_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="spaces.space",
            ),
        ),
    ]
