# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: API Test & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: poetry
    - name: Install deps
      run: poetry install
    - name: pylint
      run: poetry run pylint **/*.py
    - name: black
      run: poetry run black .
    - name: isort
      run: poetry run isort .
    - name: flake8
      run: |
        poetry run flake8 . --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --statistics
    - name: pytest
      run: poetry run pytest .
