# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: App Test & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: Install deps
      run: npm install
    - name: format
      run: npm run format
    - name: typecheck
      run: npm run typecheck
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:unit
